### ISSUE TITLE
Application error because of 401 after login

### ISSUE THREAD

**Issue by entnx-01** [grossartig/vanmoof-encryption-key-exporter#3]
Hey, I tried to login in a local started container as well as in your online version. Both times I run into an error:
`Application error: a client-side exception has occurred (see the browser console for more information).`

Google chrome console says:
`Failed to load resource: the server responded with a status of 401 (Unauthorized)`

I only have a S5 bike in my Account. The login via vanmoof homepage works and I can see my bike there.

Anyone else having that issue? 

Full console output: 
`Failed to load resource: the server responded with a status of 401 (Unauthorized)
framework-305cb810cde7afac.js:9 TypeError: Cannot read properties of null (reading 'encryptionKey')
    at index-e24d57ea1207b8d6.js:1:3705
    at Array.map (<anonymous>)
    at P (index-e24d57ea1207b8d6.js:1:3442)
    at ab (framework-305cb810cde7afac.js:9:60909)
    at ud (framework-305cb810cde7afac.js:9:72795)
    at i (framework-305cb810cde7afac.js:9:120350)
    at oO (framework-305cb810cde7afac.js:9:99102)
    at framework-305cb810cde7afac.js:9:98969
    at oF (framework-305cb810cde7afac.js:9:98976)
    at ox (framework-305cb810cde7afac.js:9:95728)
a6 @ framework-305cb810cde7afac.js:9
main-d5c9aef8f3ea3bae.js:1 TypeError: Cannot read properties of null (reading 'encryptionKey')
    at index-e24d57ea1207b8d6.js:1:3705
    at Array.map (<anonymous>)
    at P (index-e24d57ea1207b8d6.js:1:3442)
    at ab (framework-305cb810cde7afac.js:9:60909)
    at ud (framework-305cb810cde7afac.js:9:72795)
    at i (framework-305cb810cde7afac.js:9:120350)
    at oO (framework-305cb810cde7afac.js:9:99102)
    at framework-305cb810cde7afac.js:9:98969
    at oF (framework-305cb810cde7afac.js:9:98976)
    at ox (framework-305cb810cde7afac.js:9:95728)
ee @ main-d5c9aef8f3ea3bae.js:1
main-d5c9aef8f3ea3bae.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
ee @ main-d5c9aef8f3ea3bae.js:1`

**Comment by Justus-D** [comment]
This may have been resolved in #2
